import { MD3DarkTheme, MD3LightTheme, type MD3Theme } from 'react-native-paper';

export const palette = {
  forest: '#0A84FF',
  deepForest: '#0052B3',
  leaf: '#4DA3FF',
  cream: '#F5F9FF',
  sage: '#EAF3FF',
  blue: '#0A84FF',
  indigo: '#5E5CE6',
  mint: '#30D158',
  green: '#34C759',
  orange: '#FF9F0A',
  yellow: '#FFD60A',
  red: '#FF453A',
  pink: '#FF2D55',
  teal: '#32D7C6',
  ink: '#101828',
  slate: '#667085',
  cloud: '#F2F4F0',
  mist: '#E8F3EC',
  line: '#DDE7DF',
  dark: '#0B0F17',
};

export const createAppTheme = (dark: boolean): MD3Theme => ({
  ...(dark ? MD3DarkTheme : MD3LightTheme),
  roundness: 22,
  colors: {
    ...(dark ? MD3DarkTheme.colors : MD3LightTheme.colors),
    primary: palette.forest,
    onPrimary: '#FFFFFF',
    primaryContainer: dark ? '#0B2A4A' : '#DCEBFF',
    onPrimaryContainer: dark ? '#DCEBFF' : '#003566',
    secondary: palette.leaf,
    onSecondary: '#FFFFFF',
    secondaryContainer: dark ? '#0B2A4A' : '#E3F1FF',
    tertiary: palette.orange,
    tertiaryContainer: dark ? '#3E2604' : '#FFF1D6',
    error: palette.red,
    background: dark ? palette.dark : palette.cream,
    surface: dark ? '#151A24' : '#FFFFFF',
    surfaceVariant: dark ? '#1F2633' : '#EDF5FF',
    outline: dark ? '#394255' : '#D6E6FA',
    outlineVariant: dark ? '#252E3E' : '#E4E7EC',
    elevation: {
      level0: 'transparent',
      level1: dark ? '#171D28' : '#FFFFFF',
      level2: dark ? '#1B2230' : '#FFFFFF',
      level3: dark ? '#202838' : '#FFFFFF',
      level4: dark ? '#253044' : '#FFFFFF',
      level5: dark ? '#2A3750' : '#FFFFFF',
    },
  },
});
