import { MD3DarkTheme, MD3LightTheme, type MD3Theme } from 'react-native-paper';

export const palette = {
  blue: '#0A84FF',
  indigo: '#5E5CE6',
  mint: '#30D158',
  green: '#34C759',
  orange: '#FF9F0A',
  yellow: '#FFD60A',
  red: '#FF453A',
  pink: '#FF2D55',
  teal: '#32D7C6',
  ink: '#101828',
  slate: '#667085',
  cloud: '#F2F4F7',
  mist: '#EAF1FF',
  line: '#D9E2F1',
  dark: '#0B0F17',
};

export const createAppTheme = (dark: boolean): MD3Theme => ({
  ...(dark ? MD3DarkTheme : MD3LightTheme),
  roundness: 16,
  colors: {
    ...(dark ? MD3DarkTheme.colors : MD3LightTheme.colors),
    primary: palette.blue,
    onPrimary: '#FFFFFF',
    primaryContainer: dark ? '#12345A' : '#D8EAFF',
    onPrimaryContainer: dark ? '#D8EAFF' : '#06315F',
    secondary: palette.green,
    onSecondary: '#FFFFFF',
    secondaryContainer: dark ? '#13351E' : '#DDF8E6',
    tertiary: palette.orange,
    tertiaryContainer: dark ? '#3E2604' : '#FFF1D6',
    error: palette.red,
    background: dark ? palette.dark : '#F5F8FC',
    surface: dark ? '#151A24' : '#FFFFFF',
    surfaceVariant: dark ? '#1F2633' : '#EEF3FA',
    outline: dark ? '#394255' : palette.line,
    outlineVariant: dark ? '#252E3E' : '#E4E7EC',
    elevation: {
      level0: 'transparent',
      level1: dark ? '#171D28' : '#FFFFFF',
      level2: dark ? '#1B2230' : '#FFFFFF',
      level3: dark ? '#202838' : '#FFFFFF',
      level4: dark ? '#253044' : '#FFFFFF',
      level5: dark ? '#2A3750' : '#FFFFFF',
    },
  },
});
